[package]
name = "httprust"
version = "0.1.0"
authors = ["Klaas de Vries <klaasjacobdevries@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
simple_logger= "1.0"
clap = "2.33"
hyper = "0.12"
futures = "0.1"
tokio = "0.1"
tokio-signal = "0.2"
